ultrabook/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("users.urls")),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('home/', include(('ultrabook_app.urls', 'home'), namespace='home')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.loginPage, name="login"),
    path("sign-up/", views.signUp, name="sign-up"),
    path("logout/", views.sign_out, name="logout")
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse

def loginPage(request):
    if request.method == 'GET':
        return render(request, "users/login.html")
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('home:home'))
        else:
            return render(request, "users/login.html", {
                "error_message": "Invalid email or password"
            })

def signUp(request):
    if request.method == 'GET':
        return render(request, "users/sign-up.html")
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        confPassword = request.POST["confirmPassword"]

        if password == confPassword:
            try:
                user = User.objects.create_user(username=username, password=password)
                login(request, user)
                return redirect(reverse('home:home'))
            except:
                return render(request, "users/sign-up.html", {
                    "error_message": "Error creating account"
                })
        else:
            return render(request, "users/sign-up.html", {
                "error_message": "Passwords do not match"
            })
        
def sign_out(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect(reverse("users:login"))

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/login.css' %}">
    <title>Login</title>
</head>
<body class="d-flex align-items-center py-4">
    <main class="form-signin w-100 m-auto">
    <form action="/" method="post" id="login">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-semibold">Login</h1>
            <div class="form-floating"> 
                <input type="text" name="username" class="form-control bg-body-tertiary" id="floatingInput" placeholder="Username"> 
                <label for="floatingInput">Username</label> 
            </div>
    
            <div class="form-floating"> 
                <input type="password" name="password" class="form-control bg-body-tertiary" id="floatingPasswordLogin" placeholder="Password"> 
                <label for="floatingInput">Password</label> 
            </div>
    
            {% if error_message %}<p><strong class="text-danger">{{ error_message }}</strong></p>{% endif %}

            <button type="submit" name="action" class="btn btn-light w-100 py-2">Login</button>
            <hr>
            <p class="mt-3 text-body-secondary">Need an account? <a href="/sign-up">Create an account</a></p>
        </form>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/sign-up.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/login.css' %}">
    <title>Sign Up</title>
</head>
<body class="d-flex align-items-center py-4">
    <main class="form-signin w-100 m-auto">
        <form action="{% url 'users:sign-up' %}" method="post" id="login">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Create a new account</h1>
            <div class="form-floating"> 
                <input type="text" name="username" class="form-control bg-body-tertiary" id="floatingInput" placeholder="Username"> 
                <label for="floatingInput">Username</label> 
            </div>
    
            <div class="form-floating"> 
                <input type="password" name="password" class="form-control bg-body-tertiary" id="floatingPassword" placeholder="Password"> 
                <label for="floatingPassword">Password</label> 
            </div>
    
            <div class="form-floating"> 
                <input type="password" name="confirmPassword" class="form-control bg-body-tertiary" id="floatingPasswordConf" placeholder="Confirm Passowrd"> 
                <label for="floatingPasswordConf">Confirm Password</label> 
            </div>
    
            {% if error_message %}<p><strong class="text-danger">{{ error_message }}</strong></p>{% endif %}

            <button type="submit" name="action" class="btn btn-light w-100 py-2">Create Account</button>
            <hr>
            <p class="mt-3 text-body-secondary">Already have an account? <a href="/">Login</a></p>
        </form>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</body>
</html>