ultrabook/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("users.urls")),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('home/', include(('ultrabook_app.urls', 'home'), namespace='home')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ultrabook_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("new-project/", views.new_project, name="new-project"),
    path("open-project/<int:project_key>/", views.open_project, name="open-project"),
    path("upload-file/", views.upload_file, name="upload-file"),
    path("gen/", views.generate_stream, name="gen"),
    path("delete-source/<int:project_key>/<int:file_key>/", views.delete_source, name="delete-source"),
    path("delete-project/<int:project_key>/", views.delete_project, name="delete-project"),
    path("switch-model/<int:project_key>/<str:model_name>/", views.switch_model, name="switch-model"),
    path("get-model/", views.fetch_model, name="get-model"),
    path("save-system-message/", views.save_message, name='save-system-message'),
    path("create-podcast/", views.text_to_audio, name="create-podcast"),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.loginPage, name="login"),
    path("sign-up/", views.signUp, name="sign-up"),
    path("logout/", views.sign_out, name="logout")
]

ultrabook_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.functions import Now

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    desc = models.TextField()
    icon = models.TextField(db_default="stars")
    created_at = models.DateTimeField(db_default=Now())
    ai_model = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class File(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.FileField(upload_to='project_files/')
    uploaded_at = models.DateTimeField(db_default=Now())
    url = models.TextField()

    def __str__(self):
        return f"File {self.file.name} for {self.project.title}"

class Podcast(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.FileField(upload_to="podcasts/")
    created_at = models.DateTimeField(db_default=Now())

    def __str__(self):
        return f"File {self.file.name} for {self.project.title}"

class Message(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    content = models.TextField()
    is_user = models.BooleanField(db_default=True)
    timestamp = models.DateTimeField(db_default=Now())

    def __str__(self):
        return f"{'User' if self.is_user else 'AI'}: {self.content[:20]}"

ultrabook_app/views.py
import requests
import pathlib
import subprocess
import json
import threading
import tempfile
import os
import string
from urllib.parse import unquote

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import StreamingHttpResponse, JsonResponse
from django.views.decorators.cache import never_cache
from django.conf import settings
from django.core.files.base import ContentFile
from .models import Project, File, Message, Podcast

from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings, ChatOllama
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_docling import DoclingLoader
from langchain_docling.loader import ExportType
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain
from langchain_community.document_loaders import SeleniumURLLoader

from dia.model import Dia
import torch
from RealtimeTTS import TextToAudioStream, KokoroEngine

embedder = OllamaEmbeddings(model="snowflake-arctic-embed2")
text_splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=0)

OLLAMA_URL = settings.OLLAMA_BASE_URL  # Make sure this is set correctly

def get_models() -> list:
    try:
        thelist = requests.get(OLLAMA_URL + "/api/tags")
        thelist.raise_for_status()  # Ensure we handle HTTP errors
        jsondata = thelist.json()
        result = []
        for model in jsondata["models"]:
            result.append(model["model"])
        return result
    except Exception as e:
        # Optionally log or handle errors
        return []

def process_files(files, vector_store, project):
    threads = []
    for file in files:
        thread = threading.Thread(target=_process_file, args=(file, vector_store, project))
        threads.append(thread)
        thread.start()
    for thread in threads:
        thread.join()

def _process_file(file, vector_store, project):
    file_instance = File(project=project, file=file)
    file_instance.save()

    if file_instance.file.name.endswith(('.pdf', '.docx', '.xlsx', '.pptx', '.md', '.html', '.csv', '.png', '.jpeg', '.tiff', '.bmp', '.webp')):
        loader = DoclingLoader(
            file_path=file_instance.file.path,
            export_type=ExportType.DOC_CHUNKS
        )
    else:
        loader = None

    documents = loader.load() if loader else []
    filtered_documents = []
    for doc in documents:
        filtered_documents.append(
            Document(
                page_content=doc.page_content,
                id=doc.id,
                metadata={"source": file_instance.file.name}
            )
        )

    splits = text_splitter.split_documents(filtered_documents)
    vector_store.add_documents(splits)

def process_urls(urls, vector_store, project):
    threads = []
    for url in urls:
        thread = threading.Thread(target=_process_url, args=(url, vector_store, project))
        threads.append(thread)
        thread.start()
    for thread in threads:
        thread.join()

def _process_url(url, vector_store, project):
    url_file_instance = File(project=project, url=url)
    url_file_instance.save()

    loader = SeleniumURLLoader(urls=[url])
    documents = loader.load()

    filtered_documents = []
    for doc in documents:
        filtered_documents.append(
            Document(
                page_content=doc.page_content,
                id=doc.id,
                metadata={"source": url}
            )
        )

    splits = text_splitter.split_documents(filtered_documents)
    vector_store.add_documents(splits)

# Create your views here.
@login_required
def home(request):
    user_projects = Project.objects.filter(user=request.user).order_by("-created_at")
    return render(request, "ultrabook_app/home.html", {
        "projects": user_projects
    })

@login_required
def new_project(request):
    try:
        project = Project(
            user=request.user,
            title=request.POST["title"],
            desc=request.POST["desc"],
            ai_model=settings.DEFAULT_MODEL
        )
        project.save()
    except Exception as e:
        print(f"Failed to create project: {e}")

    vector_store = Chroma(
        collection_name=request.POST["title"].replace(" ", "-"),
        embedding_function=embedder,
        persist_directory="./chroma_langchain_db",
    )

    files = request.FILES.getlist('files')
    urls = request.POST['urls']

    thread1 = threading.Thread(target=process_files, args=(files, vector_store, project))
    thread1.start()

    thread2 = None
    if urls:
        thread2 = threading.Thread(target=process_urls, args=(urls.split(','), vector_store, project))
        thread2.start()

    # Wait for both threads to complete
    thread1.join()
    if urls:
        thread2.join()

    return redirect(reverse('home:open-project', kwargs={"project_key": project.pk}))

@login_required
def upload_file(request):
    selected_project = Project.objects.get(pk=request.POST["projectID"])

    vector_store = Chroma(
        collection_name=selected_project.title.replace(" ", "-"),
        embedding_function=embedder,
        persist_directory="./chroma_langchain_db",
    )

    files = request.FILES.getlist('files')
    urls = request.POST['urls']

    thread1 = threading.Thread(target=process_files, args=(files, vector_store, selected_project))
    thread1.start()

    thread2 = None
    if urls:
        thread2 = threading.Thread(target=process_urls, args=(urls.split(','), vector_store, selected_project))
        thread2.start()

    # Wait for both threads to complete
    thread1.join()
    if urls:
        thread2.join()

    return redirect(reverse('home:open-project', kwargs={"project_key": selected_project.pk}))

@login_required
def open_project(request, project_key, **kwargs):
    try:
        selected_project = Project.objects.get(pk=project_key)
        sources = File.objects.filter(project=project_key)
        models = get_models()
        conversation = Message.objects.filter(project=selected_project).order_by('timestamp')
        source_list = []

        for source in sources:
            processed_name = source.file.name.replace("project_files/", '') if source.file else source.url
            processed_name = processed_name.replace("_", " ")
            is_url = True if source.url else False
            source_list.append({
                'file': source.file,
                'processed_name': processed_name,
                'extension': processed_name.split(".")[-1],
                "file_pk": source.pk,
                "is_url": is_url
            })
        
        podcast = None
        if Podcast.objects.filter(project=selected_project).exists():
            podcast = Podcast.objects.get(project=selected_project)

        return render(request, "ultrabook_app/project.html", {
            "project": selected_project,
            "sources": source_list,
            "models": models,
            "conversation": conversation,
            "error_message": kwargs.get("error_message", None),
            "podcast_file": podcast.file.url if podcast else None
        })
    except Project.DoesNotExist:
        return HttpResponse("Project not found", status=404)
    except Exception as e:
        return HttpResponse(f"Error: {str(e)}", status=500)
    
@login_required
def generate_stream(request):
    project_id = request.POST['projectID']
    user_prompt = request.POST['prompt']
    selected_project = Project.objects.get(pk=project_id)

    # Prepare vector store & chain
    vector_store = Chroma(
        collection_name=selected_project.title.replace(' ', '-'),
        embedding_function=embedder,
        persist_directory='./chroma_langchain_db',
    )
    prompt_template = ChatPromptTemplate.from_messages([
        MessagesPlaceholder(variable_name="chat_history"),
        ('system', 'Use the context to answer:\n\n{context}\n'),
        ('human', '{input}'),
    ])
    llm = ChatOllama(model=selected_project.ai_model)
    combine_chain = create_stuff_documents_chain(llm=llm, prompt=prompt_template)
    retriever = vector_store.as_retriever()
    chain = create_retrieval_chain(retriever, combine_chain)


    messages = Message.objects.filter(project=selected_project).values('content', 'is_user')
    chat_history = chat_history = [
        {
            'content': msg['content'],
            'role': 'human' if msg['is_user'] else 'ai'
        }
        for msg in messages
    ]
    
    # Save user message immediately
    usr_msg = Message.objects.create(
        project=selected_project,
        content=user_prompt,
        is_user=True,
    )
    
    usr_msg.save()

    def stream_generator():
        for chunk in chain.stream({
            'input': user_prompt,
            'chat_history': chat_history
        }):
            text = chunk.get('answer', '')
            if text:
                yield f"data: {json.dumps({'chunk': text})}\n\n"

    response = StreamingHttpResponse(
        stream_generator(),
        content_type='text/event-stream'
    )

    response['Cache-Control'] = 'no-cache'
    return response


@login_required
def delete_source(request, project_key, file_key):
    selected_project = Project.objects.get(pk=project_key)
    selected_file = File.objects.get(pk=file_key)
    
    # Initialize Chroma vector store
    vector_store = Chroma(
        collection_name=selected_project.title.replace(" ", "-"),
        embedding_function=embedder,
        persist_directory="./chroma_langchain_db",
    )

    ids_to_delete = []
    deletion_docs = vector_store.get(include=["metadatas"])

    if selected_file.file:
        for idx, metadata in enumerate(deletion_docs["metadatas"]):

ultrabook_app/templates/ultrabook_app/home.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'ultrabook_app/styles.css' %}">
    <title>Home</title>
</head>
<body class="d-flex align-items-center py-4 bg-body">
    <main class="w-75 m-auto">
        <div class="text-end justify-content-end" id="user-container">
            <div class="dropdown p-2">
                <a href="#" data-bs-toggle="dropdown" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" aria-expanded="false">
                    <i class="bi bi-person-circle icon-lg"></i>
                </a>
                <ul class="dropdown-menu shadow">
                    <li>
                        <p class="dropdown-item">
                            {{ user.username }}
                        </p>
                    </li>
                    <li>
                        <a href="{% url 'users:logout' %}" class="dropdown-item">
                            <span class="icon pe-2">
                                <i class="bi bi-door-open-fill"></i>
                            </span>
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="header">
            <h1 class="title fw-semibold" id="heading">Welcome to ultrabook {% if user.is_authenticated %} {{ user.username }}! {% endif %}</h1>
            <div id="subheading">
                <p class="lead">Create a new project or select one below</p>
                <button id="new-project-btn" class="btn btn-light magic-border btn-lg d-flex justify-content-center align-items-center magic-text" data-bs-toggle="modal" data-bs-target="#createProjectForm"><i class="bi bi-plus large-icon"></i> New Project</button>
            </div>
            <div id="projects" class="d-flex flex-wrap">
                {% for project in projects %}
                    <div class="card me-2 mt-5 bg-light text-dark magic-border" style="width: 18rem;">
                        <a href="{% url 'home:open-project' project_key=project.pk %}" id="anchorCard">
                            <div class="card-body">
                                <i class="bi bi-{{ project.icon }} mb-5 large-icon magic-text"></i>
                                <h3 class="card-title text-truncate">{{ project.title }}</h3>
                                <p class="card-text mb-2 text-truncate">{{ project.desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div id="createProjectForm" class="modal fade" tabindex="-1" aria-labelledby="createProjectForm">
                <div class="modal-dialog modal-dialog-centered modal-lg">
                    <div class="modal-content rounded-4 shadow">
                        <div class="modal-header p-5 pb-4 border-bottom-0">
                            <h1 class="fw-semibold mb-0 fs-3">Create a new project</h1>
                            <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="close"></button>
                        </div>
                        <form action="{% url 'home:new-project' %}" method="post" enctype="multipart/form-data" id="fileForm">
                            {% csrf_token %}
                            <div class="modal-body p-5 pt-0 d-flex">
                                <div class="container">
                                    <div class="row">
                                        <div class="col">
                                            <div class="form-floating">
                                                <input type="text" name="title" class="form-control bg-body-tertiary" id="floatingTitle" placeholder="New Project" required aria-required="true">
                                                <label for="floatingTitle">New Title</label>
                                            </div>
                                            <div class="form-floating">
                                                <input type="text" name="desc" class="form-control bg-body-tertiary" id="floatingDesc" placeholder="A short description" required aria-required="true">
                                                <label for="floatingDesc">A short description</label>
                                            </div>
                                        </div>
                                        <div class="col" id="file-upload">
                                            <div id="dropzone" class="box__input">
                                                <label for="file" class="form-label" id="fileLabel"><strong >Choose files</strong><span class="box__dragndrop"> or drag them here</span></label>
                                                <input class="box__file form-control bg-body-tertiary" type="file" name="files" id="file" data-multiple-caption="{count} files selected" multiple onchange="validateFile()" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row pt-2">
                                        <div class="form-floating">
                                            <input type="text" name="urls" class="form-control bg-body-tertiary" id="floatingUrls" placeholder="URL sources to use (separate with commas)">
                                            <label for="floatingUrls" class="ps-4">URL sources to use (separate with commas)</label>
                                            <div id="chipsContainer"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-light magic-border" data-bs-dismiss="modal">Create Project</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/SplitText.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", (event) => {
            gsap.registerPlugin(SplitText);

            document.fonts.ready.then(() => {
                gsap.set("#heading", { opacity: 1 });
                gsap.set("#subheading", { opacity: 1 })
                const split = SplitText.create("#heading", {
                    type: "words",
                    onSplit: (self) => {
                        return gsap.from(self.words, {
                            y: 30,
                            opacity: 0,
                            stagger: 0.15,
                            ease: "back"
                        });
                    }
                })

                const subheading = document.getElementById("subheading")
                gsap.from(subheading, {
                    y: 30,
                    opacity: 0,
                    ease: "back"
                })
            })

            const cards = document.getElementsByClassName("card")
            gsap.from(cards, {
                y: 30,
                autoAlpha: 0,
                stagger: 0.125
            });
        });
    </script>
    {% load static %}
    <script src="{% static 'ultrabook_app/app.js' %}"></script>
</body>
</html>